name: brain_tr_gammaknife
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.8.0
  - pytorch=2.6.0
  - torchvision
  # - numpy
  - numpy<2.0  # Downgrade NumPy to a compatible version (1.26.x) for radiomics. Lots of obscene lexic here.
  - matplotlib
  - tqdm
  - pip
  - openpyxl # to read .xlsx files
  - simpleitk # medical image processing
  - scikit-learn
  - seaborn
  - pip:
      - pydicom==2.4.0
      - napari
      - pynrrd
      - pyradiomics # pyradiomics feature extraction