# Define the dataset configuration for YOLOv8 segmentation training

path: EE577_Final_Project_Files/data  # Root directory of the dataset
train: EE577_Final_Project_Files/data/images/train  # Folder containing training images
val: EE577_Final_Project_Files/data/images/val  # Folder containing validation images

nc: 1  # Number of classes (1 = brain tumor)
names: ['tumor']  # Class names

# Define image size and augmentation settings
imgsz: 512  # Image size for training
epochs: 200  # Number of training epochs
batch: 11  # Batch size
workers: 2  # Number of CPU workers for data loading
cache: true  # Cache images to RAM for faster training

# Training augmentation options
augment:
  flipud: 0.5  # Random vertical flip probability
  fliplr: 0.5  # Random horizontal flip probability
  hsv_h: 0.015  # Adjust hue
  hsv_s: 0.7  # Adjust saturation
  hsv_v: 0.4  # Adjust value
  mosaic: 1.0  # Enable mosaic augmentation

# Optimizer settings
lr0: 0.001  # Initial learning rate
momentum: 0.937  # Momentum
weight_decay: 0.0005  # Weight decay

# Enable mixed precision training for better speed
amp: true

# Save best model based on validation loss
save_period: 1  # Save model checkpoint every epoch
